<?php 
    if(empty($_SESSION)){
        session_start();
    }
    
    if ((empty($_SESSION) || ($_SESSION['rights']) !== 'admin')){
        header('Location: ../index.php');
    }
?>

<!DOCTYPE html>
<html lang="fr">
	<head><?php include('../layouts/head.phtml'); ?></head>
	
	<body>
		<header><?php include('../layouts/header.phtml'); ?></header>
		
		<main id="adminMenu">
           <nav id="sideMenu">
                <ul>
                    <li id="statistics">Statistiques</li>
                    <li id="messages">Messages</li>
                    <li id="managePoi">Gestion des points d'intérêt</li>
                    <li id="manageCategories">Gestion des catégories</li>
                    <li id="manageRights">Gestion des droits</li>
                    <li id="deleteContributor">Supprimer un contributeur</li>
                </ul>
            </nav>
            
            <div id="displayInfo">
    			<div class="PHPerrors">
    				<?php if (isset($_SESSION['errors']) == true) {
                        
                        echo('<p><span><i class="fas fa-exclamation-triangle"></i>Il y a ' . sizeof($_SESSION['errors']) . ' erreur(s) dans le formulaire !</span></p>');
                        
                        foreach($_SESSION['errors'] as $error) {
                            echo('<p>' . $error . '</p>');
                        }
                        
                        unset($_SESSION['errors']);
                    } ?>
    			</div>
            </div>
		</main>
		
        <footer><?php include('../layouts/footer.phtml'); ?></footer>
	    <script type="module" src="../JS/admin.js"></script>
	</body>
</html>