<?php session_start(); ?>

<!DOCTYPE html>
<html lang="fr">
	<head><?php include('../layouts/head.phtml'); ?></head>
	
	<body>
		<header><?php include('../layouts/header.phtml'); ?></header>
		
		<main>
		    <div class="JSerrors"></div>
			<div class="PHPerrors">
			    <?php if (isset($errors) == true) {
	                echo('<p><span><i class="fas fa-exclamation-triangle"></i>Il y a ' . sizeof($errors) . ' erreur(s) dans le formulaire !</span></p>');
	                foreach($errors as $error) {
	                    echo('<p>' . $error . '</p>');
	                }
	            } ?>
			</div>
		
            <form method="POST" action="../MVC_controller/contact_us.php" id="contactForm">
                <fieldset class="form">
                    <input type="text" name="name" id="name" size="30" placeholder="Nom"/>
    				<input type="email" name="email" id="email" size="30" placeholder="Email"/>
    				<textarea name="message" rows="15" placeholder="Mon message"></textarea>
        			<div class="button">
    				    <input class="submit" type="submit" value="Envoyer" id="confirmMessage"/>
    	                <button class="cancel" type="button">Annuler</button>
    	            </div>
    	       </fieldset>
    		</form>
		</main>

        <footer><?php include('../layouts/footer.phtml'); ?></footer>
	</body>
</html>