<?php session_start(); ?>

<!DOCTYPE html>
<html lang="fr">
	<head><?php include('../layouts/head.phtml'); ?></head>
	
	<body>
		<header><?php include('../layouts/header.phtml'); ?></header>
		
		<main id="legal">
			<h1>MENTIONS LEGALES</h1>
			<p>Conformément aux dispositions de l’article 6-III-1 de la loi n°2004-575 du 21 juin 2004 pour la confiance dans l’économie numérique, vous trouverez ci-dessous l’ensemble des informations légales relatives au présent site Internet.</p>
			
			<h2>Conditions d'utilisation</h2>
			<p>En utilisant le présent site Internet, vous reconnaissez avoir lu, compris et accepté les présentes conditions d’utilisation du site, et vous vous engagez à les respecter en intégralité et sans restriction. L’éditeur du site se réserve le droit de modifier le contenu du présent site, à tout moment et sans préavis.</p>
			<p>L’éditeur du site met en œuvre tous les moyens à sa disposition afin de fournir un contenu à jour et fiable sur son site. L’éditeur du site en collaboration avec l’hébergeur du site met en oeuvre tous les moyens à sa disposition afin de sécuriser l’hébergement du site Internet de Square Strategy en vue notamment d’empêcher toute propagation de virus informatique via le site.</p>
			<p>Toutefois, l’éditeur du site conjointement avec l’hébergeur du site déclinent toute responsabilité relative à d’éventuels dommages directs ou indirects qui pourraient avoir été engendrés par l’accès au présent site, ou par l’utilisation du site et rubrique/ou des informations qui y sont mises à disposition de l’utilisateur.</p>
			<p>Ceci inclut entre autres l’inaccessibilité, la détérioration, la destruction ou perte de données et rubrique ou la propagation de virus informatiques qui pourraient survenir sur le matériel informatique de l’utilisateur. De même, ils ne sauraient être tenu pour responsable d’une coupure temporaire ou définitive de l’accès au présent site Internet.</p>
			<p>De plus, malgré tout le soin apporté à la mise à jour régulière du présent site, l’éditeur du site décline toute responsabilité relative à d’éventuelles omissions, inexactitudes ou erreurs qui pourraient exister dans son contenu. L’utilisateur du site reconnaît en être informé, et se servir des informations contenues dans le présent site sous sa responsabilité exclusive.</p>

			<h2>Liens hypertextes</h2>
			<p>Le présent site est susceptible de contenir des liens vers d’autres sites Internet, ou d’autres ressources sur Internet.</p>
			<p>Ces liens sont proposés à simple but de complément d’information. Dans la mesure où l’éditeur du site n’a aucun contrôle sur les sites ou services en question, il ne saurait être tenu pour responsable quant aux contenus, services, ou publicités, ou tout autre matériel disponible sur ou à partir de ces sites ou ressources externes. L’activation de ces liens n’est aucunement à caractère obligatoire et l’utilisateur reconnaît les activer à ses propres risques et périls. Il appartient en outre à l’utilisateur de prendre connaissance des conditions d’utilisation particulières relatives à l’utilisation de ces autres sites Internet ou ressources sur Internet.</p>
			
			<h2>Cookies</h2>
			<p>Le site peut collecter de manière automatique certaines informations vous concernant lors d’une simple navigation sur notre site Internet, notamment : des informations concernant l’utilisation de notre site, comme les zones que vous visitez et les services auxquels vous accédez, votre adresse IP, le type de votre navigateur, vos temps d’accès. De telles informations sont utilisées exclusivement à des fins de statistiques internes, de manière à améliorer la qualité des services qui vous sont proposés. Les bases de données sont protégées par les dispositions de la loi relative à la protection juridique des bases de données.</p>

			<h2>Données personnelles</h2>
			<p>De manière générale, vous n’êtes pas tenu de nous communiquer vos données personnelles lorsque vous visitez notre site web.</p>
			<p>Cependant pour certains services proposés vous pouvez être amenés à nous communiquer des données. Tel est le cas lorsque vous remplissez le formulaire de contact en ligne. Dans tous les cas, vous pouvez refuser de fournir vos données personnelles. Dans ce cas, vous ne pourrez pas utiliser le formulaire pour nous contacter.</p>

			<h2>Droit applicable</h2>
			<p>Le présent site Internet est régi par l’application des lois françaises. Il appartient aux utilisateurs accédant au site depuis un autre pays que la France, de s’assurer que les conditions d’utilisation du présent site Internet sont conformes aux lois localement applicables dans le pays depuis lequel le site est visité.</p>

			<h2>Mise à jour des mentions légales</h2>
			<p>L’éditeur du site se réserve le droit de modifier les mentions légales à tout moment et sans préavis. Il appartient à l’utilisateur de vérifier qu’il a pris connaissance de la dernière version en date lors de ses visites sur le présent site.</p>
		</main>

        <footer><?php include('../layouts/footer.phtml'); ?></footer>
	</body>
</html>