<!DOCTYPE html>
<html lang="fr">
	<head><?php include('../layouts/head.phtml'); ?></head>
	
	<body>
		<header><?php include('../layouts/header.phtml'); ?></header>
		
		<main>
		    <div class="JSerrors"></div>
			<div class="PHPerrors">
			    <?php if (isset($errors) == true) {
                    echo('<p><span><i class="fas fa-exclamation-triangle"></i>Il y a ' . sizeof($errors) . ' erreur(s) dans le formulaire !</span></p>');
                    foreach($errors as $error) {
                        echo('<p>' . $error . '</p>');
                    }
                } ?>
			</div>
			
			<form method="POST" action="../MVC_controller/login.php" class="form" id="submitLogin">
    			<input type="text" name="login" id="login" size="30" placeholder="Login"/>
				<input type="password" name="password" id="password" size="30" placeholder="Mot de passe">
				<div class="button">
				    <input class="submit" type="submit" value="Connexion" id="confirmLogin"/>
	                <button class="cancel" type="button">Annuler</button>
	            </div>
    		</form>
		</main>

        <footer><?php include('../layouts/footer.phtml'); ?></footer>
	</body>
</html>