<!DOCTYPE html>
<html lang="fr">
	<head><?php include('../layouts/head.phtml'); ?></head>
	
	<body>
		<header><?php include('../layouts/header.phtml'); ?></header>
		
		<main>
		    <div class="JSerrors"></div>
			<div class="PHPerrors">
			    <?php if (isset($errors) == true) {
                    echo('<p><span><i class="fas fa-exclamation-triangle"></i>Il y a ' . sizeof($errors) . ' erreur(s) dans le formulaire !</span></p>');
                    foreach($errors as $error) {
                        echo('<p>' . $error . '</p>');
                    }
                } ?>
			</div>
			
            <form method="POST" action="../MVC_controller/registration.php" id="registrationForm">
	           <fieldset class="form">
                    <input type="text" name="first_name" id="first_name" size="30" placeholder="Prénom"/>
    				<input type="text" name="last_name" id="last_name" size="30" placeholder="Nom"/>
    				<input type="email" name="email" id="email" size="30" placeholder="Email"/>
    				<input type="text" name="login" id="login" size="30" placeholder="Pseudo"/>
    				<input type="password" name="password" id="password" size="30" placeholder="Mot de passe"/>
    				<input type="password" name="passwordConfirmation" id="passwordConfirmation" size="30" placeholder="Confirmez le mot de passe"/>
        			<p><em>Le champ <strong>Prénom</strong> et <strong>Nom</strong> ne peuvent contenir que des lettres (majuscules ou minuscules), des tirets ou des espaces.</em></p>
        			<p><em>Votre <strong>mot de passe</strong> doit contenir au moins 10 caractères et une majuscule. Sont autorisés les accents ainsi que les caractère spéciaux suivants: \'!#$%&@?.-_"</em></p>
        			<div class="button">
    				    <input class="submit" type="submit" value="M'inscrire" id="confirmRegistration"/>
    	                <button class="cancel" type="button">Annuler</button>
    	            </div>
    	        </fieldset>
    		</form>
		</main>

        <footer><?php include('../layouts/footer.phtml'); ?></footer>
	</body>
</html>