<?php session_start(); ?>

<!DOCTYPE html>
<html lang="fr">
	<head><?php include('../layouts/head.phtml'); ?></head>
	
	<body>
		<header><?php include('../layouts/header.phtml'); ?></header>
		
		<main>
            <p>Votre compte a bien été enregistré.</p>
            <a href="../index.php" class="submit">Retour à l'accueil</a>
		</main>

        <footer><?php include('../layouts/footer.phtml'); ?></footer>
	</body>
</html>