<?php if (empty($_SESSION)){header('Location: ../index.php');} ?>

<!DOCTYPE html>
<html lang="fr">
	<head><?php include('../layouts/head.phtml'); ?></head>
	
	<body>
		<header><?php include('../layouts/header.phtml'); ?></header>
		
		<main id="updateCard">
			
			<?php include('../layouts/errors_div.phtml'); ?>
			
			<form method="POST" action="../MVC_controller/confirm_update_poi.php" class="addPoi" enctype=multipart/form-data>
			<fieldset>
				<legend>Modifier le point d'intérêt</legend>

					<ul class='hide'>
						<li><label for="id">ID :</label></li>
						<li><input type="text" name="id" id="id" value="<?= $POIData['id'] ?>"/></li>
					</ul>
					<ul>
						<li><label for="newTitle">Titre :</label></li>
						<li><input type="text" name="newTitle" id="newTitle" data-index="<?= $POIData['id'] ?>" value="<?= $POIData['title'] ?>"/></li>
					</ul>
					<ul>
						<li><label for="newDescription">Description :</label></li>
						<li><textarea name="newDescription" id="newDescription"><?= $POIData['description'] ?></textarea></li>
					</ul>
					<ul>
						<li><label for="newWebsite">Site internet (optionnel) :</label></li>
						<li><input type="url" name="newWebsite" id="newWebsite" value="<?= $POIData['website'] ?>"/></li>
					</ul>
					<ul>
		    			<li><label for="registeredAddress">Adresse :</label></li>
		        		<li><input type="text" name="address" id="registeredAddress" value="<?= $POIData['address'] . ', ' . $POIData['zipcode'] . ' ' . $POIData['city']?>"/></li>
					</ul>
					<ul>
		    			<li><label></label></li>
		        		<li><button id="newAddressButton">Modifier l'adresse</button></li>
					</ul>
					<ul class="hide">			
		    			<li><label for="newZipcode">Code postal:</label></li>
						<li><input type="text" name="newZipcode" id="newZipcode" maxlength="5"></li>
					</ul>
					<ul class="hide" id="hiddenCity">			
		    			<li><label for="newCity">Ville :</label></li>
						<li><input type="text" name="newCity" id="newCity" disabled="disabled"/></li>
					</ul>
					<ul class="hide" id="hiddenAddress">
		    			<li><label for="newAddress">Adresse :</label></li>
		        		<li><input type="text" name="newAddress" id="newAddress"/></li>
					</ul>
					<ul class="alwaysHide">
						<li><input type="text" name="selectedNumberStreet" id="selectedNumberStreet" value="<?= $POIData['address'] ?>"/></li>
						<li><input type="text" name="selectedZipcode" id="selectedZipcode" value="<?= $POIData['zipcode'] ?>"/></li>
						<li><input type="text" name="selectedCity" id="selectedCity" value="<?= $POIData['city'] ?>"/></li>
						<li><input type="text" name="selectedLat" id="selectedLat" value="<?= $POIData['latitude'] ?>"/></li>	
						<li><input type="text" name="selectedLong" id="selectedLong" value="<?= $POIData['longitude'] ?>"/></li>
						<li><input type="text" name="selectedCityLat" id="selectedCityLat" value="<?= $POIData['cityLatitude'] ?>"/></li>	
						<li><input type="text" name="selectedCityLong" id="selectedCityLong" value="<?= $POIData['cityLongitude'] ?>"/></li>
					</ul>
					<ul>     
		        		<li><label for="category">Catégorie :</label></li>
		        			<li><select name="category" id="category">
		        				<option value="<?= $POIData['category_id'] ?>"><?= $POIData['category'] ?> (Catégorie active)</option>
				        		<?php foreach ($categories as $category) : ?>
		        					 <option value="<?= $category['id']; ?>"><?= $category['name']; ?></option>
		        				<?php endforeach ?>
		        			</select></li>
					</ul>
					<ul id="photo">     
		        		<li><label>Photo active :</label></li>
						<li><img src="<?= '../' . $POIData['photo'] ?>" alt="<?= $POIData['title'] ?>" id="registeredPhoto"/></li>
						<li><input type="hidden" name="registeredPhoto" value="<?= $POIData['photo'] ?>"/></li>
					</ul>
	                <ul id="upload">
	                	<li><label>Modifier la photo (taille maximum : 1MB; formats acceptés : .jpg, .jpeg, .git, .png) :</label></li>
	           	        <li><input type="hidden" name="MAX_FILE_SIZE" value="1048576"/></li>
	                	<li><input type="file" name="img"/></li>
	                </ul>
	                <ul id="copyrights">
	                	<li><input type="checkbox" name="copyright" id="copyright"/></li>
	                	<li><label for="copyright">Je certifie être l'auteur de cette photo et autorise son utilisation sur le site leflaneur.fr.</label></li>
	                </ul>
	                <div class="button">
					    <input class="submit" type="submit" value="Enregister les modifications" id="confirmChanges"/>
		                <button class="cancel" type="button">Annuler</button>
		            </div>
           
 			</fieldset>   		
			</form>
		</main>

        <footer><?php include('../layouts/footer.phtml'); ?></footer>
        <script type="module" src="../JS/poi.js"></script>
	</body>
</html>