<meta charset="utf-8"/>
<meta name="robots" content="noindex, nofollow">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Fontawesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
<!-- police -->
<link href="https://fonts.googleapis.com/css2?family=Blinker:wght@300&display=swap" rel="stylesheet"> 
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
<!-- JQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script> 
<!-- autocomplete jQuery -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<!-- Affichage des cartes -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>
<!-- JS -->
<script type="module" src="../JS/main.js"></script>
<script type="module" src="../JS/forms_validator.js"></script>
<!-- CSS -->
<link rel="stylesheet" href="../style/style.css" type="text/css"/>
<!-- titre -->
<title>Visitons!</title>
<!-- Open Graph data -->
<meta property="og:title" content="Le Flâneur"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="http://www.leflaneur.fr/"/>
<meta property="og:image" content="../images/flaneur.jpg"/>
<meta property="og:description" content="Le Flâneur, générateur de surprenantes, belles et curieuses ballades."/>
<!-- Twitter Card data -->
<meta name="twitter:card" content="Le Flâneur">
<meta name="twitter:site" content="@le_flaneur">
<meta name="twitter:title" content="Le Flâneur">
<meta name="twitter:description" content="Le Flâneur, générateur de surprenantes, belles et curieuses ballades.">
<meta name="twitter:creator" content="@le_flaneur_founder">
<meta name="twitter:image" content="../images/flaneur.jpg">